import { Niche, AgentLog, BusinessCase } from "@/types";

export const MOCK_NICHES: Niche[] = [
  {
    id: 1,
    name: "Kitesurfen",
    subdomain: "kitesurfen.starterkit.de",
    score: 8.4,
    demand_score: 9.1,
    competition_score: 6.2,
    cpc_estimate: 1.2,
    aov_estimate: 180,
    commission_rate: 0.08,
    status: "live",
    go_no_go: true,
    recommended_budget: 150,
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 4200,
    estimated_revenue: 840,
  },
  {
    id: 2,
    name: "Camping Anfänger",
    subdomain: "camping.starterkit.de",
    score: 7.8,
    demand_score: 8.5,
    competition_score: 5.8,
    cpc_estimate: 0.9,
    aov_estimate: 220,
    commission_rate: 0.07,
    status: "live",
    go_no_go: true,
    recommended_budget: 120,
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 3800,
    estimated_revenue: 720,
  },
  {
    id: 3,
    name: "Fotografie",
    subdomain: "fotografie.starterkit.de",
    score: 9.1,
    demand_score: 9.8,
    competition_score: 7.1,
    cpc_estimate: 1.8,
    aov_estimate: 350,
    commission_rate: 0.06,
    status: "building",
    go_no_go: true,
    recommended_budget: 200,
    created_at: "2026-03-21T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
  {
    id: 4,
    name: "Yoga Einsteiger",
    subdomain: null,
    score: 7.2,
    demand_score: 8.0,
    competition_score: 6.5,
    cpc_estimate: 1.1,
    aov_estimate: 120,
    commission_rate: 0.08,
    status: "pending_approval",
    go_no_go: null,
    recommended_budget: 100,
    created_at: "2026-03-22T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
  {
    id: 5,
    name: "Angeln",
    subdomain: null,
    score: 6.8,
    demand_score: 7.2,
    competition_score: 5.0,
    cpc_estimate: 0.8,
    aov_estimate: 160,
    commission_rate: 0.07,
    status: "rejected",
    go_no_go: false,
    recommended_budget: 0,
    created_at: "2026-03-21T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
  {
    id: 6,
    name: "Klettern",
    subdomain: null,
    score: 8.0,
    demand_score: 8.8,
    competition_score: 6.8,
    cpc_estimate: 1.4,
    aov_estimate: 280,
    commission_rate: 0.07,
    status: "discovered",
    go_no_go: null,
    recommended_budget: 160,
    created_at: "2026-03-23T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
];

export const MOCK_AGENT_LOGS: AgentLog[] = [
  {
    id: 1,
    agent_name: "research",
    action: "Scored 12 German hobby niches",
    result: "Top niche: Kitesurfen with score 8.4",
    status: "success",
    timestamp: "2026-03-24T08:00:00Z",
  },
  {
    id: 2,
    agent_name: "business_case",
    action: "Generated business case for Kitesurfen",
    result: "Go decision — recommended budget EUR 150",
    status: "success",
    timestamp: "2026-03-24T08:15:00Z",
  },
  {
    id: 3,
    agent_name: "site_builder",
    action: "Building site for Fotografie niche",
    result: "Generating 5 German SEO pages",
    status: "success",
    timestamp: "2026-03-24T08:30:00Z",
  },
  {
    id: 4,
    agent_name: "link_builder",
    action: "Searching Amazon.de products for Camping",
    result: "Found 8 products for starter kit bundle",
    status: "success",
    timestamp: "2026-03-24T08:45:00Z",
  },
  {
    id: 5,
    agent_name: "ads_manager",
    action: "Created Google Ads campaign for Kitesurfen",
    result: "Campaign ID: 123456789 — Budget EUR 150/month",
    status: "success",
    timestamp: "2026-03-24T09:00:00Z",
  },
  {
    id: 6,
    agent_name: "controller",
    action: "Monitoring all niche KPIs",
    result: "All systems normal — no anomalies detected",
    status: "success",
    timestamp: "2026-03-24T09:15:00Z",
  },
  {
    id: 7,
    agent_name: "ads_manager",
    action: "CPC spike detected on Camping campaign",
    result: "CPC exceeded threshold — pausing ad group",
    status: "warning",
    timestamp: "2026-03-24T09:30:00Z",
  },
  {
    id: 8,
    agent_name: "research",
    action: "Discovering new niches",
    result: "Error connecting to SerpAPI",
    status: "error",
    timestamp: "2026-03-24T09:45:00Z",
  },
];

export const MOCK_BUSINESS_CASE: BusinessCase = {
  niche_id: 1,
  niche_name: "Kitesurfen",
  cac: 28.5,
  ltv: 142.0,
  contribution_margin: 0.34,
  payback_period_days: 45,
  scenarios: {
    best: {
      monthly_revenue: 1200,
      monthly_spend: 150,
      roi: 7.0,
      break_even_days: 30,
    },
    base: {
      monthly_revenue: 840,
      monthly_spend: 150,
      roi: 4.6,
      break_even_days: 45,
    },
    worst: {
      monthly_revenue: 420,
      monthly_spend: 150,
      roi: 1.8,
      break_even_days: 90,
    },
  },
  recommended_budget: 150,
  go_no_go: true,
};