import { Site, Page } from "@/types";
import { Niche, AgentLog, BusinessCase } from "@/types";

export const MOCK_NICHES: Niche[] = [
  {
    id: 1,
    name: "Kitesurfen",
    subdomain: "kitesurfen.starterkit.de",
    score: 8.4,
    demand_score: 9.1,
    competition_score: 6.2,
    cpc_estimate: 1.2,
    aov_estimate: 180,
    commission_rate: 0.08,
    status: "live",
    go_no_go: true,
    recommended_budget: 150,
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 4200,
    estimated_revenue: 840,
  },
  {
    id: 2,
    name: "Camping Anfänger",
    subdomain: "camping.starterkit.de",
    score: 7.8,
    demand_score: 8.5,
    competition_score: 5.8,
    cpc_estimate: 0.9,
    aov_estimate: 220,
    commission_rate: 0.07,
    status: "live",
    go_no_go: true,
    recommended_budget: 120,
    created_at: "2026-03-20T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 3800,
    estimated_revenue: 720,
  },
  {
    id: 3,
    name: "Fotografie",
    subdomain: "fotografie.starterkit.de",
    score: 9.1,
    demand_score: 9.8,
    competition_score: 7.1,
    cpc_estimate: 1.8,
    aov_estimate: 350,
    commission_rate: 0.06,
    status: "building",
    go_no_go: true,
    recommended_budget: 200,
    created_at: "2026-03-21T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
  {
    id: 4,
    name: "Yoga Einsteiger",
    subdomain: null,
    score: 7.2,
    demand_score: 8.0,
    competition_score: 6.5,
    cpc_estimate: 1.1,
    aov_estimate: 120,
    commission_rate: 0.08,
    status: "pending_approval",
    go_no_go: null,
    recommended_budget: 100,
    created_at: "2026-03-22T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
  {
    id: 5,
    name: "Angeln",
    subdomain: null,
    score: 6.8,
    demand_score: 7.2,
    competition_score: 5.0,
    cpc_estimate: 0.8,
    aov_estimate: 160,
    commission_rate: 0.07,
    status: "rejected",
    go_no_go: false,
    recommended_budget: 0,
    created_at: "2026-03-21T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
  {
    id: 6,
    name: "Klettern",
    subdomain: null,
    score: 8.0,
    demand_score: 8.8,
    competition_score: 6.8,
    cpc_estimate: 1.4,
    aov_estimate: 280,
    commission_rate: 0.07,
    status: "discovered",
    go_no_go: null,
    recommended_budget: 160,
    created_at: "2026-03-23T10:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
    traffic: 0,
    estimated_revenue: 0,
  },
];

export const MOCK_AGENT_LOGS: AgentLog[] = [
  {
    id: 1,
    agent_name: "research",
    action: "Scored 12 German hobby niches",
    result: "Top niche: Kitesurfen with score 8.4",
    status: "success",
    timestamp: "2026-03-24T08:00:00Z",
  },
  {
    id: 2,
    agent_name: "business_case",
    action: "Generated business case for Kitesurfen",
    result: "Go decision — recommended budget EUR 150",
    status: "success",
    timestamp: "2026-03-24T08:15:00Z",
  },
  {
    id: 3,
    agent_name: "site_builder",
    action: "Building site for Fotografie niche",
    result: "Generating 5 German SEO pages",
    status: "success",
    timestamp: "2026-03-24T08:30:00Z",
  },
  {
    id: 4,
    agent_name: "link_builder",
    action: "Searching Amazon.de products for Camping",
    result: "Found 8 products for starter kit bundle",
    status: "success",
    timestamp: "2026-03-24T08:45:00Z",
  },
  {
    id: 5,
    agent_name: "ads_manager",
    action: "Created Google Ads campaign for Kitesurfen",
    result: "Campaign ID: 123456789 — Budget EUR 150/month",
    status: "success",
    timestamp: "2026-03-24T09:00:00Z",
  },
  {
    id: 6,
    agent_name: "controller",
    action: "Monitoring all niche KPIs",
    result: "All systems normal — no anomalies detected",
    status: "success",
    timestamp: "2026-03-24T09:15:00Z",
  },
  {
    id: 7,
    agent_name: "ads_manager",
    action: "CPC spike detected on Camping campaign",
    result: "CPC exceeded threshold — pausing ad group",
    status: "warning",
    timestamp: "2026-03-24T09:30:00Z",
  },
  {
    id: 8,
    agent_name: "research",
    action: "Discovering new niches",
    result: "Error connecting to SerpAPI",
    status: "error",
    timestamp: "2026-03-24T09:45:00Z",
  },
];

export const MOCK_BUSINESS_CASE: BusinessCase = {
  niche_id: 1,
  niche_name: "Kitesurfen",
  cac: 28.5,
  ltv: 142.0,
  contribution_margin: 0.34,
  payback_period_days: 45,
  scenarios: {
    best: {
      monthly_revenue: 1200,
      monthly_spend: 150,
      roi: 7.0,
      break_even_days: 30,
    },
    base: {
      monthly_revenue: 840,
      monthly_spend: 150,
      roi: 4.6,
      break_even_days: 45,
    },
    worst: {
      monthly_revenue: 420,
      monthly_spend: 150,
      roi: 1.8,
      break_even_days: 90,
    },
  },
  recommended_budget: 150,
  go_no_go: true,
};

// ─── REAL API ENDPOINT PATHS (Varun's Backend) ───────────────────────────────
// Use these when Varun's backend is running on http://localhost:8000

export const API_ROUTES = {
  // Niches
  niches:               "/api/v1/niches",
  nicheById:            (id: number) => `/api/v1/niches/${id}`,
  nicheApprove:         (id: number) => `/api/v1/niches/${id}/approve`,
  nicheReject:          (id: number) => `/api/v1/niches/${id}/reject`,
  nicheBusinessCase:    (id: number) => `/api/v1/niches/${id}/business-case`,
  nicheDiscover:        "/api/v1/niches/discover",

  // Sites
  sites:                "/api/v1/sites",
  sitePages:            (id: number) => `/api/v1/sites/${id}/pages`,
  sitePublish:          (id: number) => `/api/v1/sites/${id}/publish`,

  // Links
  links:                (nicheId: number) => `/api/v1/links/${nicheId}`,
  linksRefresh:         (nicheId: number) => `/api/v1/links/${nicheId}/refresh`,

  // Campaigns
  campaigns:            "/api/v1/campaigns",
  campaignPause:        (id: number) => `/api/v1/campaigns/${id}/pause`,
  campaignResume:       (id: number) => `/api/v1/campaigns/${id}/resume`,

  // Alerts
  alerts:               "/api/v1/alerts",
  alertResolve:         (id: number) => `/api/v1/alerts/${id}/resolve`,

  // Approvals
  approvals:            "/api/v1/approvals",
  approvalApprove:      (id: number) => `/api/v1/approvals/${id}/approve`,
  approvalReject:       (id: number) => `/api/v1/approvals/${id}/reject`,

  // Agent
  agentLogs:            "/api/v1/agent-logs",
  agentStatus:          "/api/v1/system/agent-status",
  budgetAllocations:    "/api/v1/budget-allocations",
  pauseAll:             "/api/v1/system/pause-all",
  runController:        "/api/v1/system/run-controller",
};

// ─── MOCK SITES DATA ─────────────────────────────────────────────────────────

export const MOCK_SITES: Site[] = [
  {
    id: 1,
    niche_id: 1,
    niche_name: "Kitesurfen",
    subdomain: "kitesurfen.starterkit.de",
    status: "live",
    page_count: 5,
    last_published: "2026-03-23T10:00:00Z",
    traffic_30d: 4200,
    created_at: "2026-03-20T10:00:00Z",
  },
  {
    id: 2,
    niche_id: 2,
    niche_name: "Camping Anfänger",
    subdomain: "camping.starterkit.de",
    status: "live",
    page_count: 4,
    last_published: "2026-03-22T10:00:00Z",
    traffic_30d: 3800,
    created_at: "2026-03-21T10:00:00Z",
  },
  {
    id: 3,
    niche_id: 3,
    niche_name: "Fotografie",
    subdomain: "fotografie.starterkit.de",
    status: "building",
    page_count: 0,
    last_published: null,
    traffic_30d: 0,
    created_at: "2026-03-23T10:00:00Z",
  },
  {
    id: 4,
    niche_id: 4,
    niche_name: "Yoga Einsteiger",
    subdomain: "yoga.starterkit.de",
    status: "draft",
    page_count: 2,
    last_published: null,
    traffic_30d: 0,
    created_at: "2026-03-23T10:00:00Z",
  },
];

export const MOCK_PAGES: Page[] = [
  {
    id: 1,
    niche_id: 1,
    page_type: "landing",
    url: "https://kitesurfen.starterkit.de",
    content: "<h1>Kitesurfen Anfänger Guide</h1><p>Alles was du für den Einstieg ins Kitesurfen brauchst. Von der Ausrüstung bis zum ersten Kurs — wir haben die besten Empfehlungen für dich zusammengestellt.</p>",
    meta_title: "Kitesurfen Anfänger — Starter Kit & Guide 2026",
    meta_description: "Dein kompletter Kitesurfen Starter Guide. Die besten Produkte, Kurse und Tipps für Anfänger.",
    is_published: true,
    published_at: "2026-03-23T10:00:00Z",
    affiliate_link_count: 8,
  },
  {
    id: 2,
    niche_id: 1,
    page_type: "beginner_guide",
    url: "https://kitesurfen.starterkit.de/anfaenger-guide",
    content: "<h1>Kitesurfen lernen — Der ultimative Anfänger Guide</h1><p>Schritt für Schritt zum ersten erfolgreichen Kitesurfen. Lerne die Grundlagen, die richtige Ausrüstung und die besten Spots in Deutschland.</p>",
    meta_title: "Kitesurfen lernen — Anfänger Guide 2026",
    meta_description: "Lerne Kitesurfen von Grund auf. Tipps, Tricks und die beste Ausrüstung für Einsteiger.",
    is_published: true,
    published_at: "2026-03-23T10:00:00Z",
    affiliate_link_count: 5,
  },
  {
    id: 3,
    niche_id: 1,
    page_type: "starter_kit",
    url: "https://kitesurfen.starterkit.de/starter-kit",
    content: "<h1>Das perfekte Kitesurfen Starter Kit</h1><p>Wir haben die 8 besten Produkte für Kitesurfen Anfänger ausgewählt. Qualität getestet, Preise verglichen.</p>",
    meta_title: "Kitesurfen Starter Kit — Top 8 Produkte 2026",
    meta_description: "Das beste Kitesurfen Starter Kit für Anfänger. Getestete Produkte mit Amazon Bewertungen.",
    is_published: true,
    published_at: "2026-03-23T10:00:00Z",
    affiliate_link_count: 8,
  },
  {
    id: 4,
    niche_id: 2,
    page_type: "landing",
    url: "https://camping.starterkit.de",
    content: "<h1>Camping Anfänger — Dein Starter Guide</h1><p>Alles was du für dein erstes Camping Abenteuer brauchst. Die besten Produkte für Einsteiger.</p>",
    meta_title: "Camping Anfänger — Starter Kit & Guide 2026",
    meta_description: "Dein kompletter Camping Starter Guide für Anfänger. Zelt, Schlafsack und mehr.",
    is_published: true,
    published_at: "2026-03-22T10:00:00Z",
    affiliate_link_count: 6,
  },
];